name: documentation
on: [push]
jobs:
  # This job will try to build the documentation using Doxygen.
  make-docs:
    # Target OS: Ubuntu.
    runs-on: ubuntu-latest
    # Use bash for all commands.
    defaults:
      run:
        shell: bash
    # Set of commands to be run.
    steps:
    - name: HOPE THIS WORKS
      working-directory: ${{github.workspace}}/build
      run: echo "HELLO MAIN"
      if: contains('refs/heads/main', github.ref)
    - name: HOPE THIS WORKS AGAIN
      working-directory: ${{github.workspace}}/build
      run: echo "HELLO FRANCO-TEST"
      if: contains('refs/heads/franco-test', github.ref)
    # Install CMake and Doxygen.
    - name: Install dependencies
      working-directory: ${{github.workspace}}
      run: sudo apt install cmake doxygen graphviz
      # Install pip for python3.
    - name: Install pip3
      working-directory: ${{github.workspace}}
      run: sudo apt install python3-pip
      # Install python3 dependencies (numpy and matplotlib).
    - name: Install python3 dependencies
      working-directory: ${{github.workspace}}
      run: sudo pip3 install numpy matplotlib
    # Clone the repository.
    - uses: actions/checkout@v2
    # Create the build space.
    - name: Create build directory
      working-directory: ${{github.workspace}}
      run: mkdir ${{github.workspace}}/build
    # Configure CMake.
    - name: Invoke CMake
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DBUILD_DOC=ON -DQUIET_DOXYGEN=NO
    # Run Doxygen to create the documentation.
    - name: Build documentation using Doxygen
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --target doc
  # This job should deploy the documentation generated above. Since the
  # published documentation should correspond to the stable version of
  # the project, we publish only when pushing on main.
  deploy-docs:
    # Run this action only on the main branch
    if: contains('refs/heads/main', github.ref)
    # Do this only if the make-docs job succeeded
    needs: make-docs
    # Target OS: Ubuntu.
    runs-on: ubuntu-latest
    # Use bash for all commands.
    defaults:
      run:
        shell: bash
    # Set of commands to be run.
    steps:
    # Deploy the documentation to GitHub Pages.
    - name: Deploy documentation.
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ${{github.workspace}}/doc/html
